stages:
  - testing
  - security

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

sast:
  stage: security

secret_detection:
  stage: security

go_unit_tests:
  image: golang:1.23.1-alpine
  stage: testing
  script:
    - apk add --no-cache curl
    - echo "Running tests"
    - mkdir -p coverage
    - go mod tidy
    - go test -coverprofile=./coverage/cover.out -coverpkg=. -covermode=atomic .
    - echo "Uploading coverage report"
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r ./coverage/cover.out
  coverage: '/total:\s+\(statements\)\s+\d+.\d+\%/'
