name: code-analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for better SonarQube analysis

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Run Tests
        run: go test -v -coverprofile=coverage.out -coverpkg=./... -covermode=atomic ./...

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=innotegrity
            -Dsonar.projectKey=innotegrity_go-mod-xerrors
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.coverage.exclusions=**/*_test.go

      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
