name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Create GitHub Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: innotegrity/github-actions/check-out-code@main
      - uses: innotegrity/github-actions/create-release-from-changelog@main
